---
title: "Métodos de diseño y Análisis de Experimentos"
subtitle: "Tarea 03"
author:
  - "Rivera Torres Francisco de Jesús"
  - "Rodríguez Maya Jorge Daniel"
  - "Samayoa Donado Víctor Augusto"
  - "Trujillo Bariios Georgina"
date: "Marzo 26, 2019"
output:
  pdf_document:
    toc: false
    number_sections: true
    fig_caption: true
    highlight: kate
    df_print: kable
    includes:
      in_header: tex/header.tex
fontsize: 11pt
documentclass: article
classoption: twoside
fig_align: "center"
---

```{r setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.height = 3)

# Se cargan las librerias a utilizar
# library(tidyverse)
library(readxl)
library(scales)
library(grid)
library(kableExtra)
library(latex2exp)
```


# Ejercicio 1
Teniendo un diseño completamente al azar, unifactorial, de efectos fijos con 3 tratamientos y 4 repeticiones para cada uno.

## 1.1	 Completa todos los espacios vacios de la tabla de ANOVA:

\begin{table}[H]
\caption{Tabla ANOVA}
\centering
\begin{tabular}{c|ccccc}
\toprule
FV          &  GL       & Sum Sq & Mean Sq & F- value & P-value  \\
\midrule
Tratamiento & t-1 = 2    &        & F*CME = 0.06583571     &  5.6429  &   .025806 (0.01) / .025806 (0.05)\\
\midrule
Error       & n-t = 9    &  CME*(n-t) = 0.105003     & 0.011667&          &          \\
Total       & n-1 = 11  &        &         &          &          \\
\bottomrule
\end{tabular}
\end{table}

## 1.2	 ¿Cuál es el modelo? 

$y_{i,j} = \mu_{i} +  e_{i,j}$


## 1.3	 ¿Cuál es la hipótesis nula?     

$H_{0}: \mu_{1} =  \mu_{2} =  \mu_{3}$

## 	1.4 Con un nivel de significancia $\alpha =.01$, ¿qué cuantil de la distribución $F$ usarías para determinar la zona de rechazo?¿Rechazarías $H_{0}?



## 	1.5 Con un nivel de significancia $\alpha =.05$, ¿qué cuantil de la distribución $F$ usarías para determinar la zona de rechazo?¿Rechazarías $H_{0}?

# Ejercicio 2
Se quiere contrastar la efectividad de 3 diferentes repelentes para insectos, para hacerlo se corrió un pequeño experimento con 12 viajeros de una excursión al Amazonas, aleatoriamente se determinó qué repelente se aplicaría cada viajero y al final del viaje se contó el número de piquetes que cada uno tenía.


# Ejercicio 3
Una compañía de pisos desea indagar en la resistencia de 5 diferentes materiales para piso y para ello somete 4 piezas de cada tipo de material a pruebas de resistencia, midiendo el tiempo en segundos que tarda cada material para quebrarse.


