---
title: "Métodos de diseño y Análisis de Experimentos"
subtitle: "Tarea 01"
author:
  - "Rivera Torres Francisco de Jesús"
  - "Rodríguez Maya Jorge Daniel"
  - "Samayoa Donado Víctor Augusto"
  - "Trujillo Bariios Georgina"
date: "Febrero 19, 2019"
output:
  pdf_document:
    toc: false
    number_sections: true
    fig_caption: true
    highlight: kate
    df_print: kable
    includes:
      in_header: tex/header.tex
fontsize: 11pt
documentclass: article
classoption: twoside
fig_align: "center"
---

```{r setup, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, fig.height = 3)

# Se cargan las librerias a utilizar
library(tidyverse)
library(readxl)
library(scales)
library(grid)
library(kableExtra)
library(latex2exp)
```


# Reconocimiento del problema.

En ciertas comunidades rurales se observan altas tasas de absentismo escolar. Se sabe que son diversas las causas de este problema, entre ellas destacan las siguientes: contexto social violento o frágil, dificultades de acceso a la escuela, desnutrición y enfermedades digestivas contagiosas. Por ello, un grupo de investigación se pregunta si la acción de dos tratamientos (uno contra la desnutrición y otro contra las enfermedades digestivas contagiosas) o su interacción pueden tener efectos de disminución sobre el absentismo escolar.

> "Para dimensionar la importancia que tienen las escuelas rurales en México, basta mencionar que, de acuerdo a cifras oficiales, casi un 56% de los preescolares, un 58% de las primarias, un 57% de las secundarias y un 30% de los establecimientos de media superior existentes durante el ciclo escolar 2013-2014, se ubicaban en localidades menores a 2500 habitantes (INEE, 2015, p. 66). criterio que –hay que recordar– es el que usa el INEGI para definir a una población rural. A estos planteles asisten casi 7 millones de alumnos de todas las entidades federativas del país^[https://educacion.nexos.com.mx/?p=378]".

> "Para el caso de alumnos que acuden  a escuelas rurales multigrado; es decir, en donde un maestro atiende a estudiantes de más de un grado escolar; cabe señalar que, durante el ciclo escolar ya mencionado,  esa modalidad constituyó un 53% de las escuelas preescolares del país, un 51% de las primarias y un 25.4% de las telesecundarias (inee, 2015, p. 305)^[https://educacion.nexos.com.mx/?p=378]".

# Definir factores o niveles
Se definen dos factores: una nueva formula de nutrientes (factor 1) y un medicamento para ciertos parásitos (factor 2) que se incorpora al desayuno escolar. Por lo tanto, tenemos cuatro tratamientos: 1) desayuno escolar fortificado nutricionalmente y con medicamento añadido, 2) desayuno escolar con nueva fórmula nutritiva pero sin medicamento, 3) desayuno escolar usual con medicamento y 4) desayuno ordinario (tratamiento de control).

# Unidad experimental
La unidad experimental es el alumnado agregado de cada una de las escuelas. Mientras que las submuestras son los alumnos individualmente (unidades observacionales más elementales). En este caso el efecto del tratamiento de un alumno ante enfermedades digestivas puede tener externalidades positivas en el resto de la escuela (por ello, definimos la unidad experimental como la escuela o alumnado agregado).

# Variable de respuesta
Tasa de absentismo escolar diaria. Suponiendo que no tenemos limitaciones logísticas ni de recursos, podríamos recopilar la información diaria de absentismo en cada escuela y comparar posteriormente diferentes medidas (por ejemplo, media y varianza mensual de absentismo en cada escuela) y tendencia de los distintos tratamientos (esto podría realizarse durante algunos meses o años).

# Elección del diseño experimental
Tasa de absentismo escolar diaria. Suponiendo que no tenemos limitaciones logísticas ni de recursos, podríamos recopilar la información diaria de absentismo en cada escuela y comparar posteriormente diferentes medidas (por ejemplo, media y varianza mensual de absentismo en cada escuela) y tendencia de los distintos tratamientos (esto podría realizarse durante algunos meses o años).

# Determinación del número de repeticiones
Debido a que la unidad experimental son las escuelas, idealmente nos gustaría que todas las escuelas participarán. Pero debido a que en la práctica esto puede llegar a ser prohibitivo en términos de costos y logística. Por tal motivo, se buscará tener 5 u.e para cada uno de los tratamientos mencionados previamente^[Se buscó información sobre el número de escuelas rurales en México, pero no se encontró dicha información como para calcular un tamaño muestral. Se encontró https://www.inee.edu.mx/portalweb/informe2018/04_informe/capitulo_0502.html pero no indica qué es lo que se entiende por primaria general, indigena y comunitaria. Esto es, ¿cuáles caen dentro de la categoría de primaria rural?].

Se sabe que el error experimental puede ser originado por las siguientes causas:

1. **Variacion natural entre u.e.**
    Podemos minimizar esta fuente de error al aleatorizar la selección de los tratamientos para cada una de las u.e. con lo cual variables como contexto social violeto o fragil, pobreza familiar y dificultades de acceso a la escuela.
    En dado caso, se buscaría una aleatorización por bloque. Donde el bloque quedaría definido por el nivel socioeconómico de la zona en la que se localiza cada escuela (unidad experimental).
    
2. **Variabilidad en la medicion de la respuesta**
    Se buscará siempre obtener la medición de absentismo a partir de las faltas escolares registradas en la lista de asistencia y considerar aquellas que tengas algún tipo de justificante (e.g. algún justificante médico).
    
3. **Incapacidad de reproducir las condiciones de los tratamientos exactamente de una u.e. a otra**
    Se buscará minimizar esta fuente de error mediante los seguimientos mensuales para tratar de mantener un apego a cada uno de los tratamientos durante todo el estudio.
    
4. **Interaccion de tratamientos y u.e**
    Esta parte la tratamos de minimizar al determinar cada escuela como u.e. Sin embargo, no podemos de controlar del todo esta interacción ya que pueden existir familiares/amigos que perteneezcan a diferentes u.e. pero que interactuen entre si fuera de la escuela.

5. **Cualquier otro factor externo que afecte las características medidas**
    No existe mucho que se pueda hacer en este caso ya que son cuestiones externas/ajenas al estudio que probablemtne no se previeron.

# Hacer el experimento y colectar los datos
Se buscará dar seguimiento durante dos periodos escolares completos. Esto es, desde Agosto 2019 hasta Julio 2021. De esta forma se podrán recolectar datos duran 24 meses.

En la primera visita se propone generar un perfil completo de los estudiantes (submuestras) en cada una de las escuelas (unidad experimental) de tal forma que se conocerá información como:

- Contexto social al inicio del estudio
- Nivel de pobreza familiar al inicio del estudio
- Dificultades de acceso a la escuela al inicio del estudio
- Grado escolar al inicio del estudio
- Sexo
- Edad
- Tamaño del núcleo familiar al inicio del estudio
- Número de hermanos en edad escolar al inicio del estudio
- Número de hermanos en la misma escuela (unidad experimental) al inicio del estudio
- Número de hermanos en otra escuela (unidad experimental) al inicio del estudio

Se propone realizar visitas de seguimiento mensual en cada una de las escuelas (unidad experimental) con el objetivo de recbar información como el apego al tratamiento de los alumnos (submuestra), así como entrevistas con los profesores para identificar problemas de ausentismo con los laumnos.

Al finalizar los 24 meses, se realizará otro perfil completo de los estudiantes (submuestra) donde se conocerá información como:

- Contexto social al final del estudio
- Nivel de pobreza familiar al final del estudio
- Dificultades de acceso a la escuela al final del estudio
- Grado escolar al final del estudio
- Tamaño del núcleo familiar al final del estudio
- Número de hermanos en edad escolar al final del estudio
- Número de hermanos en la misma escuela (unidad experimental) al final del estudio
- Número de hermanos en otra escuela (unidad experimental) al inicio del estudio

Cabe destacar que esta última parte tendrá un sesgo al tener únicamente información de estudiantes que abandonaron la escuela en el transcurso del estudio.

# Efectuar el análisis estadístico
Con la información recabada previamente, se procederá a generar un estadístico que indique de forma mensual la proporción de absentismo en cada una de las escuelas (unidades experimentales).

También se podrá calcular este estadístico desglosado por cada una de las variables obtenidas en las entrevistas iniciales/finales del estudio.

# Obtención de conclusiones

Como primer objetivo del estudio será decidir si existe alguna diferencia significativa entre los factores definidos.

Como segundo objetivo, se buscará determinar si existen diferencias significativas entre los factores definidos a partir del estadístico de absentismo desglosado por cada una de las variables definidas en las entrevistas/finales del estudio.

Lo anterior ayudará a determinar si existen grupos de alto riesgo de entre toda la población estudiada o determinar si hay factores que tienen un mejor impacto en ciertos grupos de las submuestras.